# Generated by Django 6.0.2 on 2026-02-04 11:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Downloadable files',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Lift'), (1, 'Stairlift'), (2, 'Stair'), (3, 'Escalator')])),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(blank=True, choices=[(None, 'Unknown'), (False, 'Not working'), (True, 'Working')], default=None, null=True)),
                ('friendly_name', models.CharField(blank=True, max_length=100)),
                ('lift_width', models.PositiveIntegerField(blank=True, help_text='in millimeters', null=True)),
                ('lift_depth', models.PositiveIntegerField(blank=True, help_text='in millimeters', null=True)),
                ('visually_impaired_ok', models.BooleanField(default=False)),
                ('assistance_required', models.BooleanField(default=False)),
                ('number_of_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('steps_height', models.PositiveIntegerField(blank=True, default=0, help_text='in millimeters', null=True)),
                ('handrail', models.IntegerField(choices=[(0, 'No'), (1, 'Right'), (2, 'Left'), (3, 'Both')], default=0)),
                ('handrail_height', models.PositiveIntegerField(blank=True, help_text='in millimeters', null=True)),
                ('pathway_mode', models.IntegerField(choices=[(3, 'No (Moving walkway)'), (4, 'Yes (Escalator)')], default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='lifts')),
            ],
            options={
                'ordering': ('stop', 'type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RampRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Stop ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('location_type', models.IntegerField(choices=[(0, 'Stop or platform'), (1, 'Station'), (2, 'Entrance/Exit'), (3, 'Generic node'), (4, 'Boarding area'), (5, 'Area')], default=1)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('wheelchair_boarding', models.IntegerField(choices=[(0, 'No info'), (1, 'Yes'), (2, 'No')], default=0)),
                ('visually_impaired_path', models.IntegerField(choices=[(0, 'No info for the stop'), (1, 'Yes'), (2, 'No'), (3, 'Only in some areas')], default=0)),
                ('platform_code', models.CharField(blank=True, max_length=20)),
                ('cardinal_direction', models.CharField(blank=True, choices=[('N', 'North'), ('E', 'East'), ('W', 'West'), ('S', 'South')], max_length=1)),
                ('step_free_route_information_available', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('outside_station_unique_id', models.CharField(blank=True, max_length=50)),
                ('blue_badge_car_parking', models.BooleanField(default=False)),
                ('blue_badge_car_park_spaces', models.IntegerField(blank=True, null=True)),
                ('taxi_ranks_outside_station', models.BooleanField(default=False)),
                ('bus_stop_outside_station', models.BooleanField(default=False)),
                ('train_station', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='stops')),
                ('status', models.IntegerField(choices=[(0, 'To do'), (1, 'Working'), (2, 'Completed'), (3, 'Validated')], default=0)),
                ('accessible_entrance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.stop')),
                ('accessible_exit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.stop')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='stations.city')),
                ('parent_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stations.stop')),
            ],
            options={
                'ordering': ('location_type', '-level', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='stations.city')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RampLevelPath',
            fields=[
                ('ramproutes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stations.ramproutes')),
            ],
            bases=('stations.ramproutes',),
        ),
        migrations.CreateModel(
            name='StepFreeInterchangeInfo',
            fields=[
                ('ramproutes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stations.ramproutes')),
                ('distance', models.IntegerField(blank=True, null=True)),
            ],
            bases=('stations.ramproutes',),
        ),
        migrations.CreateModel(
            name='Segnalazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='segnalazioni')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segnalazioni', to='stations.lift')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Segnalazioni',
                'db_table': 'voxpop_segnalazione',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='ramproutes',
            name='from_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramp_routes', to='stations.stop'),
        ),
        migrations.AddField(
            model_name='ramproutes',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramps', to='stations.stop'),
        ),
        migrations.AddField(
            model_name='ramproutes',
            name='to_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.stop'),
        ),
        migrations.CreateModel(
            name='LineStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='stations.line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stations.stop')),
            ],
            options={
                'ordering': ('line', 'order'),
            },
        ),
        migrations.AddField(
            model_name='lift',
            name='from_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.stop'),
        ),
        migrations.AddField(
            model_name='lift',
            name='intermediate_area1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.stop'),
        ),
        migrations.AddField(
            model_name='lift',
            name='intermediate_area2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.stop'),
        ),
        migrations.AddField(
            model_name='lift',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifts', to='stations.stop'),
        ),
        migrations.AddField(
            model_name='lift',
            name='to_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.stop'),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stations.stop')),
                ('min_gap', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Min gap (mm)')),
                ('max_gap', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Max gap (mm)')),
                ('average_gap', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Average gap (mm)')),
                ('min_step', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Min step (mm)')),
                ('max_step', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Min step (mm)')),
                ('average_step', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Average step (mm)')),
                ('designated_level_access_point', models.BooleanField(default=False)),
                ('level_access_by_manual_ramp', models.BooleanField(default=False)),
                ('additional_accessibility_info', models.TextField(blank=True, null=True)),
                ('direction_towards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.stop')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='stations.line')),
                ('location_of_level_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.stop')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
