# Generated by Django 6.0.2 on 2026-02-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='platform_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
