# Generated by Django 4.1.5 on 2023-02-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='handrail_height',
            field=models.FloatField(default=False, help_text='height in centimeters'),
        ),
        migrations.AlterField(
            model_name='lift',
            name='lift_heigth',
            field=models.FloatField(blank=True, help_text='height in centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='lift',
            name='lift_width',
            field=models.FloatField(blank=True, help_text='width in centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='lift',
            name='steps_height',
            field=models.FloatField(default=0, help_text='height in centimeters'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='location_type',
            field=models.IntegerField(choices=[(0, 'Stop or platform'), (1, 'Station'), (2, 'Entrance/Exit'), (3, 'Generic node'), (4, 'Boarding area'), (5, 'Area')], default=1),
        ),
    ]
