# Generated by Django 4.1.5 on 2023-01-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformservice',
            name='level_access_by_manual_ramp',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RampRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramp_routes', to='stations.stop')),
                ('to_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stations.stop')),
            ],
        ),
    ]
