# Generated by Django 4.1.5 on 2023-02-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_lift_handrail_height_alter_lift_lift_heigth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, help_text='Insert the color code: es. #DF0101', max_length=20, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='stop',
            name='lines',
            field=models.ManyToManyField(to='stations.line'),
        ),
    ]
