# Generated by Django 4.1.5 on 2023-01-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_platformservice_level_access_by_manual_ramp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RampLevelPath',
            fields=[
                ('ramproutes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stations.ramproutes')),
            ],
            bases=('stations.ramproutes',),
        ),
        migrations.CreateModel(
            name='StepFreeInterchangeInfo',
            fields=[
                ('ramproutes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stations.ramproutes')),
                ('distance', models.IntegerField(blank=True, null=True)),
            ],
            bases=('stations.ramproutes',),
        ),
    ]
