# Generated by Django 4.1.5 on 2023-01-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_ramplevelpath_stepfreeinterchangeinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ('name',)},
        ),
    ]
