# Generated by Django 4.1.5 on 2023-02-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_line_stop_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='lines',
            field=models.ManyToManyField(related_name='lines', to='stations.line'),
        ),
    ]
