# Generated by Django 4.1.5 on 2023-01-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_stop_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
