# Generated by Django 4.1.5 on 2023-02-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_remove_stair_stairlift_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lift',
            old_name='lift_type',
            new_name='type',
        ),
    ]
