# Generated by Django 4.1.5 on 2023-02-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_alter_stop_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramproutes',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ramps', to='stations.stop'),
            preserve_default=False,
        ),
    ]
