# Generated by Django 4.1.5 on 2023-02-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_rename_lift_type_lift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lift',
            name='type',
            field=models.IntegerField(choices=[(0, 'Lift'), (1, 'Stairlift'), (2, 'Stair'), (3, 'Escalator')]),
        ),
    ]
