# Generated by Django 4.1.5 on 2023-02-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_stop_level_alter_lift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='level',
            field=models.IntegerField(),
        ),
    ]
