# Generated by Django 4.1.5 on 2023-02-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_services_direction_towards_services_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='lift',
            name='image',
            field=models.ImageField(blank=True, upload_to='lifts'),
        ),
        migrations.AddField(
            model_name='stop',
            name='image',
            field=models.ImageField(blank=True, upload_to='stops'),
        ),
        migrations.AlterField(
            model_name='line',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stop',
            name='lines',
            field=models.ManyToManyField(blank=True, related_name='stations', to='stations.line'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
