# Generated by Django 4.1.5 on 2023-02-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_lift_image_stop_image_alter_line_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='cardinal_direction',
            field=models.CharField(blank=True, choices=[('N', 'Nord'), ('E', 'East'), ('W', 'West'), ('S', 'South')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stop',
            name='outside_station_unique_id',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stop',
            name='platform_code',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
