# Generated by Django 4.1.5 on 2023-02-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_alter_stop_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lift',
            name='number_of_steps',
        ),
    ]
