# Generated by Django 4.1.5 on 2023-02-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_remove_lift_number_of_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='steps_height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
