# Generated by Django 4.1.5 on 2023-02-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_rename_assistance_requested_lift_assistance_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lift',
            old_name='from_areas',
            new_name='from_area',
        ),
        migrations.RenameField(
            model_name='lift',
            old_name='intermediate_areas',
            new_name='intermediate_area1',
        ),
        migrations.RenameField(
            model_name='lift',
            old_name='intermediate_areas_two',
            new_name='intermediate_area2',
        ),
        migrations.RenameField(
            model_name='lift',
            old_name='to_areas',
            new_name='to_area',
        ),
    ]
