# Generated by Django 4.1.5 on 2023-02-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_alter_lift_steps_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='lift',
            name='number_of_steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lift',
            name='steps_height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
