# Generated by Django 4.1.5 on 2023-02-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_lift_number_of_steps_alter_lift_steps_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='steps_height',
            field=models.FloatField(default=0),
        ),
    ]
