# Generated by Django 4.1.5 on 2023-02-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_rename_from_areas_lift_from_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lift',
            old_name='lift_notes',
            new_name='notes',
        ),
    ]
