# Generated by Django 4.1.5 on 2023-02-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_rename_lift_notes_lift_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='lift_heigth',
            field=models.PositiveIntegerField(blank=True, help_text='height in millimeters', null=True),
        ),
        migrations.AlterField(
            model_name='lift',
            name='lift_width',
            field=models.PositiveIntegerField(blank=True, help_text='width in millimeters', null=True),
        ),
    ]
