# Generated by Django 4.1.5 on 2023-02-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_alter_lift_lift_heigth_alter_lift_lift_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lift',
            old_name='lift_heigth',
            new_name='lift_height',
        ),
    ]
