# Generated by Django 4.1.5 on 2023-02-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_rename_lift_heigth_lift_lift_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lift',
            old_name='stop_id',
            new_name='stop',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='accessible_entrance_id',
            new_name='accessible_entrance',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='accessible_exit_id',
            new_name='accessible_exit',
        ),
        migrations.AlterField(
            model_name='stop',
            name='cardinal_direction',
            field=models.CharField(blank=True, choices=[('N', 'North'), ('E', 'East'), ('W', 'West'), ('S', 'South')], max_length=1),
        ),
        migrations.AlterField(
            model_name='stop',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Stop ID'),
        ),
    ]
