# Generated by Django 4.1.5 on 2023-02-12 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0017_route_routestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='lines',
        ),
        migrations.AlterField(
            model_name='routestation',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='stations.route'),
        ),
        migrations.AlterField(
            model_name='routestation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stations.stop'),
        ),
    ]
